/* ══════════════════════════════════════
COURSE DATA
══════════════════════════════════════ */

export const COURSES = [
  {
    id:1, title:"Full Stack Web Development with React & Node.js",
    instructor:"Priya Nair", instructorTitle:"Senior Engineer @ Google",
    instructorAvatar:"PN", rating:4.9, reviews:8420, students:42300,
    duration:"48h 30m", lessons:124, level:"Intermediate",
    category:"Web Dev", lang:"English",
    price:2499, originalPrice:8999,
    progress:78, enrolled:true, lastWatched:"React Context API",
    tags:["React","Node.js","MongoDB","REST API","JWT"],
    gradient:"linear-gradient(135deg,#0d2040 0%,#1a0d40 50%,#071828 100%)",
    accent:"#3b82f6", accentGlow:"rgba(59,130,246,0.3)",
    icon:"💻", badge:"Bestseller",
    description:"Master full-stack web development from scratch. Build real-world projects with React, Node.js, Express & MongoDB. Deploy to AWS.",
    outcomes:["Build production-ready web apps","REST API design","Authentication & Authorization","Cloud deployment"],
    nextLesson:"Custom Hooks Deep Dive",
    certificate:false, updated:"Mar 2026",
  },
  {
    id:2, title:"Machine Learning & Deep Learning with PyTorch",
    instructor:"Dr. Arjun Mehta", instructorTitle:"ML Researcher @ IIT Delhi",
    instructorAvatar:"AM", rating:4.8, reviews:5610, students:28900,
    duration:"62h 15m", lessons:186, level:"Advanced",
    category:"AI / ML", lang:"English",
    price:3299, originalPrice:11999,
    progress:45, enrolled:true, lastWatched:"Backpropagation",
    tags:["Python","PyTorch","Neural Networks","CNN","Transformers"],
    gradient:"linear-gradient(135deg,#0a1a28 0%,#1a0a30 50%,#080f1a 100%)",
    accent:"#a78bfa", accentGlow:"rgba(167,139,250,0.3)",
    icon:"🤖", badge:"Top Rated",
    description:"From linear regression to cutting-edge transformers. Implement ML algorithms from scratch and train production ML models.",
    outcomes:["Neural network architecture","Computer Vision","NLP with transformers","Model deployment"],
    nextLesson:"Attention Mechanism",
    certificate:false, updated:"Feb 2026",
  },
  {
    id:3, title:"UI/UX Design Mastery: Figma to Production",
    instructor:"Sneha Kulkarni", instructorTitle:"Lead Designer @ Swiggy",
    instructorAvatar:"SK", rating:4.9, reviews:3280, students:19400,
    duration:"28h 45m", lessons:87, level:"Beginner",
    category:"Design", lang:"English",
    price:1999, originalPrice:6999,
    progress:100, enrolled:true, lastWatched:"Design System Complete",
    tags:["Figma","UX Research","Prototyping","Design Systems","Accessibility"],
    gradient:"linear-gradient(135deg,#280c17 0%,#1a0828 50%,#0c0618 100%)",
    accent:"#f472b6", accentGlow:"rgba(244,114,182,0.3)",
    icon:"🎨", badge:"Completed",
    description:"Learn professional UI/UX design from wireframes to polished interfaces. Create a complete design system and handoff to developers.",
    outcomes:["Figma proficiency","User research methods","Prototyping & testing","Design system creation"],
    nextLesson:null,
    certificate:true, updated:"Jan 2026",
  },
  {
    id:4, title:"AWS Solutions Architect — Associate Certification",
    instructor:"Vikram Iyer", instructorTitle:"AWS Certified, Ex-Amazon",
    instructorAvatar:"VI", rating:4.7, reviews:9120, students:51000,
    duration:"36h 20m", lessons:108, level:"Intermediate",
    category:"Cloud", lang:"English",
    price:2799, originalPrice:9499,
    progress:22, enrolled:true, lastWatched:"IAM Policies",
    tags:["AWS","EC2","S3","Lambda","CloudFormation","VPC"],
    gradient:"linear-gradient(135deg,#1a1000 0%,#2a1a00 50%,#0c0a00 100%)",
    accent:"#f0a500", accentGlow:"rgba(240,165,0,0.3)",
    icon:"☁️", badge:"Hot",
    description:"Prepare for the AWS SAA-C03 exam with hands-on labs. Covers all core AWS services, architecture best practices and exam strategies.",
    outcomes:["Core AWS services","High availability design","Security best practices","Exam passing strategy"],
    nextLesson:"EC2 Auto Scaling",
    certificate:false, updated:"Mar 2026",
  },
  {
    id:5, title:"Advanced TypeScript & System Design",
    instructor:"Rahul Gupta", instructorTitle:"Staff Engineer @ Flipkart",
    instructorAvatar:"RG", rating:4.8, reviews:2840, students:14200,
    duration:"42h 10m", lessons:136, level:"Advanced",
    category:"Web Dev", lang:"English",
    price:2999, originalPrice:10499,
    progress:0, enrolled:false, lastWatched:null,
    tags:["TypeScript","Design Patterns","Microservices","System Design","gRPC"],
    gradient:"linear-gradient(135deg,#061828 0%,#0d1040 50%,#060c20 100%)",
    accent:"#22d3ee", accentGlow:"rgba(34,211,238,0.3)",
    icon:"⚙️", badge:"New",
    description:"Master TypeScript generics, decorators and design patterns. Design scalable distributed systems used at FAANG companies.",
    outcomes:["TypeScript mastery","Design patterns","Distributed systems","Interview preparation"],
    nextLesson:null,
    certificate:false, updated:"Mar 2026",
  },
  {
    id:6, title:"DevOps & Kubernetes: From Zero to Production",
    instructor:"Aditya Shah", instructorTitle:"DevOps Lead @ Razorpay",
    instructorAvatar:"AS", rating:4.7, reviews:4120, students:22800,
    duration:"55h 00m", lessons:162, level:"Intermediate",
    category:"DevOps", lang:"English",
    price:2699, originalPrice:9199,
    progress:0, enrolled:false, lastWatched:null,
    tags:["Docker","Kubernetes","CI/CD","Terraform","Prometheus"],
    gradient:"linear-gradient(135deg,#0a1a10 0%,#081828 50%,#050e08 100%)",
    accent:"#4ade80", accentGlow:"rgba(74,222,128,0.3)",
    icon:"🚀", badge:"Trending",
    description:"Build and deploy containerized applications with Docker & Kubernetes. Set up complete CI/CD pipelines and monitor production workloads.",
    outcomes:["Docker & K8s","CI/CD pipelines","Infrastructure as Code","Production monitoring"],
    nextLesson:null,
    certificate:false, updated:"Feb 2026",
  },
  {
    id:7, title:"Data Structures & Algorithms for FAANG",
    instructor:"Pooja Reddy", instructorTitle:"SDE @ Microsoft",
    instructorAvatar:"PR", rating:4.9, reviews:15600, students:86400,
    duration:"80h 00m", lessons:248, level:"All Levels",
    category:"DSA", lang:"English",
    price:3499, originalPrice:12999,
    progress:0, enrolled:false, lastWatched:null,
    tags:["Arrays","Trees","Graphs","DP","LeetCode","System Design"],
    gradient:"linear-gradient(135deg,#1a0828 0%,#200a30 50%,#0e0620 100%)",
    accent:"#f472b6", accentGlow:"rgba(244,114,182,0.3)",
    icon:"🧮", badge:"Bestseller",
    description:"Crack coding interviews at top tech companies. 500+ curated problems with detailed explanations, patterns and time/space complexity analysis.",
    outcomes:["All major data structures","Problem-solving patterns","Interview readiness","Top company questions"],
    nextLesson:null,
    certificate:false, updated:"Mar 2026",
  },
  {
    id:8, title:"Python for Data Science & Analytics",
    instructor:"Dr. Kavita Joshi", instructorTitle:"Data Scientist @ Paytm",
    instructorAvatar:"KJ", rating:4.8, reviews:6750, students:38200,
    duration:"34h 30m", lessons:104, level:"Beginner",
    category:"Data Science", lang:"English",
    price:1999, originalPrice:6999,
    progress:0, enrolled:false, lastWatched:null,
    tags:["Python","Pandas","NumPy","Matplotlib","SQL","EDA"],
    gradient:"linear-gradient(135deg,#0a1828 0%,#081420 50%,#040c14 100%)",
    accent:"#00d4aa", accentGlow:"rgba(0,212,170,0.3)",
    icon:"📊", badge:"Popular",
    description:"Learn Python for data analysis, visualization and machine learning. Work with real datasets from Kaggle and build end-to-end data pipelines.",
    outcomes:["Data manipulation","Statistical analysis","Data visualization","ML basics"],
    nextLesson:null,
    certificate:false, updated:"Jan 2026",
  },
];

export const CATEGORIES = ["All", "Web Dev", "AI / ML", "Design", "Cloud", "DevOps", "DSA", "Data Science"];
export const LEVELS = ["All Levels", "Beginner", "Intermediate", "Advanced"];
export const SORT_OPTS = ["Most Popular", "Highest Rated", "Newest", "Price: Low to High", "Price: High to Low"];

export const NAV = [
  {
    group:"MAIN",
    items:[
      {icon:"⊞",label:"Dashboard",id:"dashboard"},
      {icon:"📚",label:"My Courses",id:"courses",active:true,badge:4},
      {icon:"🔍",label:"Explore",id:"explore"},
      {icon:"📝",label:"Assignments",id:"assignments",badge:3},
      {icon:"🏅",label:"Grades & GPA",id:"grades"},
      {icon:"📅",label:"Schedule",id:"schedule"},
    ]
  },
  {
    group:"COMMUNITY",
    items:[
      {icon:"💬",label:"Messages",id:"messages",badge:2},
      {icon:"🔔",label:"Notifications",id:"notif",badge:5},
      {icon:"🏆",label:"Leaderboard",id:"leaderboard"},
      {icon:"👥",label:"Community",id:"community"},
    ]
  },
  {
    group:"ACCOUNT",
    items:[
      {icon:"👤",label:"Profile",id:"profile"},
      {icon:"⚙️",label:"Settings",id:"settings"},
    ]
  },
];

const courseData = { COURSES, CATEGORIES, LEVELS, SORT_OPTS, NAV };
export default courseData;